import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import process from 'node:process';

/**
 * Writes a copy of the extension bundle that turns the pairing blocks on.
 *
 * The `qrCodePairing` flag is read once while the bundle evaluates, so it has
 * to be set before the extension loads. Prepending it to the bundle is the
 * reproducible way to do that: load this one file as a custom extension and the
 * blocks are there, load `dist/` and they are not. That difference is what the
 * rollback check in the acceptance criteria exercises.
 *
 * The output is local to the working copy and is not a release artifact.
 *
 * Usage: pnpm run build:flagged [errorCorrectionLevel]
 */
const levels = ['L', 'M', 'Q', 'H'] as const;
type Level = (typeof levels)[number];

const requested = process.argv[2];
if (requested !== undefined && !isLevel(requested)) {
  throw new Error(`Error correction level must be one of ${levels.join(', ')}.`);
}
const level: Level | undefined = requested;

const bundlePath = 'dist/webrtc-qrcode-pairing.js';
const outputDirectory = 'local';
const outputPath = `${outputDirectory}/webrtc-qrcode-pairing.flagged.js`;

const bundle = await readFile(bundlePath, 'utf8');
const prelude = [
  '// Generated by scripts/build-flagged.ts. Do not commit; this is a local verification aid.',
  '// The pairing blocks are off by default, so the flag is set before the bundle evaluates.',
  'globalThis.__TWQP_FEATURE_FLAGS__ = {qrCodePairing: true};',
  ...(level ? [`globalThis.__TWQP_QR_CONFIG__ = {errorCorrectionLevel: '${level}'};`] : []),
  ''
].join('\n');

await mkdir(outputDirectory, {recursive: true});
await writeFile(outputPath, `${prelude}\n${bundle}`);

process.stdout.write(
  [
    `Wrote ${outputPath} (${level ?? 'default M'} error correction).`,
    `Load it as a custom extension: file://${resolve(outputPath)}`,
    ''
  ].join('\n')
);

function isLevel(value: string): value is Level {
  return (levels as readonly string[]).includes(value);
}
